Admin_Panel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('Admin_Panel.routers')),
    path('', include('main.urls')),

]

main/urls.py
from django.urls import path
from main.filters import ProjectsLanguageLevelFiltersView
from main.views import index, main

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('main/', main, name='main'),
    path('api/projects/<str:language>/<str:level>/', ProjectsLanguageLevelFiltersView.as_view()),
]

users/urls.py
from django.urls import path

from users.views import UserLoginView, UserLogoutView, UserRegistration

app_name = 'users'

urlpatterns = [

    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegistration.as_view(), name='register'),

]

main/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from users.models import User


class Project(models.Model):
    '''
    Модель продуктов
    '''
    NO = 'Не выбрано'
    PYTHON = 'Python'
    JS = 'JS'
    C = 'C'
    C__ = 'C++'
    C_ = 'C#'
    VISUAL_BASIC = 'Visual Basic'
    SQL = 'SQL'
    PHP = 'PHP'

    LANGUAGE_CHOICES = (
        (NO, 'Не выбрано'),
        (PYTHON, 'Python'),
        (JS, 'JS'),
        (C__, 'C++'),
        (C_, 'C#'),
        (VISUAL_BASIC, 'Visual Basic'),
        (SQL, 'SQL'),
        (PHP, 'PHP'),
    )

    name = models.CharField(max_length=200, name='name')
    description = models.TextField(null=False, blank=False, name='description')
    level = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1),
                                                               MaxValueValidator(10)])
    programming_language = models.CharField(choices=LANGUAGE_CHOICES, verbose_name='programming_language',
                                            max_length=50, default=NO)
    check = models.BooleanField(default=False, name='check')
    date_created = models.DateTimeField(auto_now_add=True)
    id_telegram = models.CharField(max_length=15,verbose_name='ID_Телеграм', null=True, blank=True)
    username = models.CharField(max_length=30, verbose_name='Имя Телеграм', null=True, blank=True)
    show_author = models.BooleanField(default=False, verbose_name='Показывать Автора')
    is_active = models.BooleanField(default=True, name='is_active')

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def __str__(self) -> str:
        return f'Project {self.name} от {self.date_created}'


class UserProjectCompleted(models.Model):
    '''
    Модель пользователей выполнившие проекты
    '''


class UserProjectCompleted(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, name='user')
    project = models.ForeignKey(Project, on_delete=models.PROTECT, name='project')

    class Meta:
        verbose_name = 'Пользователь выполнивший проект'
        verbose_name_plural = "Пользователи выполнившие проект"

    def __str__(self) -> str:
        return f'Пользователь {self.user.username} выполнил проект {self.project.name}'

    def get_users_completed_project(self, project_id) -> set:
        return UserProjectCompleted.objects.all().filter(project_id=project_id)

    def get_projects_completed_user(self, user_id) -> set:
        return UserProjectCompleted.objects.all().filter(user_id=user_id)

users/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models


class User(AbstractUser):
    id_telegramm = models.IntegerField(null=True, blank=True, name='id_telegramm')
    image = models.ImageField(upload_to='users_image', blank=True)
    rating = models.DecimalField(max_digits=2, decimal_places=1, default=0.0, name='rating')
    open_profile = models.BooleanField(default=True, name='open_profile')
    pro_profile = models.BooleanField(default=False, name='pro_profile')

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self) -> str:
        return f'{self.username}'

users/forms.py
import hashlib
import random

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

    # def save(self, commit=True):
    #     user = super(UserCreationForm, self).save()
    #     user.is_active = False
    #     salt = hashlib.sha1(str(random.random()).encode('utf-8')).hexdigest()[:6]
    #     user.activation_key = hashlib.sha1((user.email + salt).encode('utf-8')).hexdigest()
    #     user.save()
    #     return user

main/views.py
from django.shortcuts import render


def index(request):
    '''Главная страница сайта'''
    return render(request, 'main/index.html')


def main(request):
    '''Основная страница'''
    return render(request, 'main/main.html')

users/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView

from users.forms import UserLoginForm, UserRegistrationForm
from users.models import User


class UserLoginView(LoginView):
    template_name = 'login.html'
    form_class = UserLoginForm


class UserLogoutView(LogoutView):
    next_page = '/'


class UserRegistration(FormView):
    model = User
    template_name = 'register.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:login')

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        messages.error(request, 'Проверьте заполнение формы')
        return redirect(self.success_url)

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'scss/main/index.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="substrate">
        <div class="container">
            <div class="bg-figures">
                <img src="{% static 'images/main/rhombus.svg' %}" class="figures rhombus" alt="rhombus">
                <img src="{% static 'images/main/cube.svg' %}" alt="cube" class="figures cube">
                <img src="{% static 'images/main/figure.svg' %}" alt="figure" class="figures fig">
            </div>
            <div class="wrapper">
                <header>
                    <a href="#" class="logo"><img src="{% static 'images/main/Logo.svg' %}" alt="logo" class="logo--img"><img src="{% static 'images/main/code_logo.svg' %}" alt="logo" class="logo--code"></a>
                    <div class="tagline">
                        <p class="tagline__text">The best Telegram Bot for practice at coding and much more!</p>
                        <p class="tagline__text">Find small project that suits for you and get better</p>
                    </div>
                    <a href="https://t.me/code_chest_bot" class="btn btn--main">See In Telegram</a>
                </header>

                <section class="media">
                    <div class="media__item">
                        <div class="media__head">
                            <a href="#" class="media__label"><img src="{% static 'images/main/great_practice.svg' %}" alt="label"></a>
                            <a href="#" class="media__link">Great Practice</a>
                        </div>
                        <div class="media__body">
                            With us you can easily get ideas and plan for small projects, so you don’t need to find it by yourself and get a great practice!
                        </div>
                    </div>
                    <div class="media__item">
                        <div class="media__head">
                            <a href="#" class="media__label"><img src="{% static 'images/main/track_progress.svg' %}" alt="label"></a>
                            <a href="#" class="media__link">Track Progress</a>
                        </div>
                        <div class="media__body">
                            Track your progress while building this simple projects. There’re a rating system so you’ll never be bored!
                        </div>
                    </div>
                    <div class="media__item">
                        <div class="media__head">
                            <a href="#" class="media__label"><img src="{% static 'images/main/customize.svg' %}" alt="label"></a>
                            <a href="#" class="media__link">Customize</a>
                        </div>
                        <div class="media__body">
                            You can customize your profile and connect with other developers so you may even find your new co-worker
                        </div>
                    </div>
                    <div class="media__item">
                        <div class="media__head">
                            <a href="#" class="media__label"><img src="{% static 'images/main/support.svg' %}" alt="label"></a>
                            <a href="#" class="media__link">24/7 Support</a>
                        </div>
                        <div class="media__body">
                            If you’ve got some trouble with  your project or something else you can easily write us and will help as soon as we can
                        </div>
                    </div>
                    <div class="media__item">
                        <div class="media__head">
                            <a href="#" class="media__label"><img src="{% static 'images/main/languages.svg' %}" alt="label"></a>
                            <a href="#" class="media__link">Languages</a>
                        </div>
                        <div class="media__body">
                            You can choose between different Programming Languages like Python, JavaScript, Ruby and many others
                        </div>
                    </div>
                    <div class="media__item">
                        <div class="media__head">
                            <a href="#" class="media__label"><img src="{% static 'images/main/build_yourself.svg' %}" alt="label"></a>
                            <a href="#" class="media__link">Build Yourself</a>
                        </div>
                        <div class="media__body">
                            Want to be part of our community? So you can easily create your own project and upload it, probably it will get much of popularity
                        </div>
                    </div>
                </section>

                <footer>
                    <p>See Us On</p>
                    <div class="social">
                        <a href="#"><img src="{% static 'images/main/tiktok.svg' %}" alt="tiktok"></a>
                        <a href="#"><img src="{% static 'images/main/twitter.svg' %}" alt="twitter"></a>
                        <a href="#"><img src="{% static 'images/main/youtube.svg' %}" alt="youtube"></a>
                        <a href="#"><img src="{% static 'images/main/discord.svg' %}" alt="discord"></a>
                    </div>
                </footer>
            </div>
        </div>
    </div>
</body>
</html>

main/templates/main/main.html
{% extends 'main/base.html' %}

{% block title %}Code Chest{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h5><a href="{% url 'users:logout' %}">Выйти</a></h5>

        <h1>Code Chest Admin and API</h1>
        <p> Привет, {{ user.username }}</p>
    {% else %}
        <h5><a href="{% url 'users:login' %}">Войдите для продолжения</a> или <a href="{% url 'users:register' %}">зарегистрируйтесь!</a>
        </h5>


        <h1>Code Chest Admin and API</h1>

    {% endif %}
{% endblock %}

users/templates/login.html
{% extends 'main/base.html' %}
{% block title %}Вход{% endblock %}

{% block content %}
    {% if user.is_authenticated %}

        <p>Вы уже выполнили вход</p>
        <a href="{% url 'users:logout' %}">Выйти</a>

    {% else %}

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="next" value="{{ next }}">
            <input type="submit" value="Войти">
        </form>
    {% endif %}
{% endblock %}

users/templates/register.html
{% extends 'main/base.html' %}
{% block title %}Регистрация{% endblock %}

{% block content %}
    {% if form.errors %}
        {{ form.errors|escape }}
        <button type="button" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    {% endif %}
    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
    </form>
{% endblock %}